version: 2.1
jobs:
  build:
 
    docker:
      - image: circleci/golang:1.15.8
    working_directory: ~/project
    steps:
      - checkout
   
      - run:
          name: Run File
          command: |
            mkdir test && cd test 
            go run ../main.go
            go env
            echo $pwd
            ls
            


